const ARC_TESTNET_CHAIN_ID = 5042002
const ARC_TESTNET_USDC_ADDRESS = '0x3600000000000000000000000000000000000000'
const DEFAULT_MARKET_PROOF_PRICE_USDC = 0.001
const DEFAULT_ESCROW_DEPOSIT_USDC = 0.1

const DATA_MODES = Object.freeze(['replay', 'live'])
const EXECUTION_MODES = Object.freeze(['mock', 'live'])
const CONFIDENCE_LEVELS = Object.freeze(['none', 'low', 'medium', 'high', 'prime'])

module.exports = {
  ARC_TESTNET_CHAIN_ID,
  ARC_TESTNET_USDC_ADDRESS,
  DEFAULT_MARKET_PROOF_PRICE_USDC,
  DEFAULT_ESCROW_DEPOSIT_USDC,
  DATA_MODES,
  EXECUTION_MODES,
  CONFIDENCE_LEVELS,
}
